// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"oakhouse-release-v1.11.0/config"
	"oakhouse-release-v1.11.0/database"
	"oakhouse-release-v1.11.0/handler"
	"oakhouse-release-v1.11.0/repository"
	"oakhouse-release-v1.11.0/service"
)

// Injectors from wire.go:

func InitializeApp() (*AppServer, func(), error) {
	// Initialize app server using existing Init method
	appServer := NewAppServer().Init()
	
	// No cleanup needed for now
	cleanup := func() {}
	
	return appServer, cleanup, nil
}